const Ziggy = {"url":"http:\/\/toggl-clone.test","port":null,"defaults":{},"routes":{"sanctum.csrf-cookie":{"uri":"sanctum\/csrf-cookie","methods":["GET","HEAD"]},"login":{"uri":"login","methods":["GET","HEAD"]},"timer":{"uri":"\/","methods":["GET","HEAD"]},"projects":{"uri":"projects","methods":["GET","HEAD"]},"clients":{"uri":"clients","methods":["GET","HEAD"]},"tags":{"uri":"tags","methods":["GET","HEAD"]},"users":{"uri":"users","methods":["GET","HEAD"]},"logout":{"uri":"logout","methods":["POST"]},"time-entries.index":{"uri":"api\/time-entries","methods":["GET","HEAD"]},"time-entries.store":{"uri":"api\/time-entries","methods":["POST"]},"time-entries.show":{"uri":"api\/time-entries\/{time_entry}","methods":["GET","HEAD"],"parameters":["time_entry"]},"time-entries.update":{"uri":"api\/time-entries\/{time_entry}","methods":["PUT","PATCH"],"parameters":["time_entry"]},"time-entries.destroy":{"uri":"api\/time-entries\/{time_entry}","methods":["DELETE"],"parameters":["time_entry"]},"projects.index":{"uri":"api\/projects","methods":["GET","HEAD"]},"projects.store":{"uri":"api\/projects","methods":["POST"]},"projects.show":{"uri":"api\/projects\/{project}","methods":["GET","HEAD"],"parameters":["project"]},"projects.update":{"uri":"api\/projects\/{project}","methods":["PUT","PATCH"],"parameters":["project"]},"projects.destroy":{"uri":"api\/projects\/{project}","methods":["DELETE"],"parameters":["project"]},"clients.index":{"uri":"api\/clients","methods":["GET","HEAD"]},"clients.store":{"uri":"api\/clients","methods":["POST"]},"clients.show":{"uri":"api\/clients\/{client}","methods":["GET","HEAD"],"parameters":["client"]},"clients.update":{"uri":"api\/clients\/{client}","methods":["PUT","PATCH"],"parameters":["client"]},"clients.destroy":{"uri":"api\/clients\/{client}","methods":["DELETE"],"parameters":["client"]},"tags.index":{"uri":"api\/tags","methods":["GET","HEAD"]},"tags.store":{"uri":"api\/tags","methods":["POST"]},"tags.show":{"uri":"api\/tags\/{tag}","methods":["GET","HEAD"],"parameters":["tag"]},"tags.update":{"uri":"api\/tags\/{tag}","methods":["PUT","PATCH"],"parameters":["tag"]},"tags.destroy":{"uri":"api\/tags\/{tag}","methods":["DELETE"],"parameters":["tag"]},"storage.local":{"uri":"storage\/{path}","methods":["GET","HEAD"],"wheres":{"path":".*"},"parameters":["path"]}}};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
  Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };

export function route(name, params) {
    // The global Ziggy object is added by the route()->toScript() call in app.blade.php
    return window.route(name, params);
}
